### PR TITLE
Age Calculator

### PR DESCRIPTION
**Pull request by RajRocky999**

### CODE REVIEW

**Comment by RajRocky999** [comment]
we can calcualte age by this calculator

**Comment by RajRocky999** [comment]
We can check date

**Review by nirajpdn — CHANGES_REQUESTED** [review]
Please add separate folder `Age Calculator` inside Javascript folder.

**Review by nirajpdn — CHANGES_REQUESTED** [review]
Also create separate folder 'Calender using Js' inside Javascript folder.

**Comment by RajRocky999** [comment]
I don't have more idea about how to create folder

**Pull request closed without merging**
