### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pragya2056**
The hacktoberfest feature picture

### CODE REVIEW

**Review by nirajpdn — CHANGES_REQUESTED** [review]
@Pragya2056 , Could you please update the contributors section also in this PR?

**Comment by Pragya2056** [comment]
sure

**Comment by Pragya2056** [comment]
The link for contributors section is good. 
Some glitch on github has delayed the update. If it is not updated in the next 10-12 hours. We can look at it again. 
@nirajpdn

**Comment by nirajpdn** [comment]
> The link for contributors section is good. Some glitch on github has delayed the update. If it is not updated in the next 10-12 hours. We can look at it again. @nirajpdn

Okay thanks. Merging the PR for now.

**Pull request merged**
