### PR TITLE
add string-methods and array problem

### PR DESCRIPTION
**Pull request by Ashvin0740**
String methods 

and remove duplicate from the Array problem

### CODE REVIEW

**Review by nirajpdn — CHANGES_REQUESTED** [review]
Please keep these files inside Javascript folder

**Review by Ashvin0740 — COMMENTED** [review]
adding string method into the javascript folder

**Review by Ashvin0740 — COMMENTED** [review]
added

**Review by 1teacher1 — APPROVED** [review]
LGTM. Thanks @Ashvin0740  for your contributions.
Don't forget to ⭐️ the repo.

**Pull request merged**
